allow form inputs to accept values
surface-ui/surface pull request #448
Opened 2021-07-02 00:47 UTC by simonmcconnell

Fixes #447.

This PR allows developers to add the `values` prop to form input fields.  The docs for the components list the `values` prop but when attempting to use it, the compiliation will fail.

2021-07-02 05:54 UTC, miguel-s requested changes
Thanks for the PR ❤️ lgtm!

Could you run the formatter again to make the tests pass?

2021-07-02 08:57 UTC, Malian commented
@miguel-s I am wondering if we should keep `events_to_opts` and `opts_to_attrs` and chain both functions or if we should create a new function `events_to_attrs`, wdyt?

2021-07-02 16:11 UTC, miguel-s approved these changes

2021-07-02 16:13 UTC, miguel-s commented
@Malian I kept those two function separate, because `opts_to_attrs` is the piece I want to replace with https://github.com/phoenixframework/phoenix_html/pull/331 once it's released (probably together with a cleanup refactor). Been waiting for that release for ages now 😅

2021-07-04 11:26 UTC, Malian commented
@miguel-s Sorry, I was not clear.

In the PR I see 12 times the following piece of code: `assigns |> events_to_opts() |> opts_to_attrs()`. I suggest to replace these pieces of code with a new function `events_to_attrs`.

```elixir
def events_to_attrs(assigns) do
  assigns
  |> events_to_opts()
  |> opts_to_attrs()
end
```

Maybe it's a bad optimisation but I feel that the intent is clearer. Feel free to move forward if my proposition is not relevant ;)

2021-07-05 15:26 UTC, miguel-s commented
@Malian Ah yes I get it now 👍 That would make things clearer and less risk for errors when changing things.

@simonmcconnell would you mind adding this helper function and apply it where needed?

2021-07-07 00:58 UTC, simonmcconnell commented
Sure.  I'll get to it asap.

2021-07-10 06:47 UTC, merged

2021-07-10 06:48 UTC, miguel-s commented
Thank you @simonmcconnell!